from src.config.default import _CN as cfg

cfg.LOFTR.MATCH_COARSE.MATCH_TYPE = 'sinkhorn'
cfg.LOFTR.MATCH_COARSE.SPARSE_SPVS = False
cfg.TRAINER.MSLR_MILESTONES = [3, 6, 9, 12, 17, 20, 23, 26, 29]
cfg.TRAINER.SEED = 42
cfg.TRAINER.CANONICAL_BS = 16
cfg.TRAINER.CANONICAL_LR = 0.001
cfg.TRAINER.WARMUP_STEP = 1000
cfg.TRAINER.GRADIENT_CLIPPING = 1.0
cfg.TRAINER.TRUE_BATCH_SIZE = 64

cfg.LOFTR.RESOLUTION = (8, 2)
cfg.LOFTR.MATCH_COARSE.MATCH_TYPE = 'sinkhorn'
